<?php

declare(strict_types=1);

/*
 * ApimaticCalculatorLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ApimaticCalculatorLib\Tests\Controllers;

use ApimaticCalculatorLib\ApimaticCalculatorClient;
use ApimaticCalculatorLib\Tests\ClientFactory;
use Core\TestCase\CoreTestCase;
use Core\Types\CallbackCatcher;
use PHPUnit\Framework\TestCase;

class BaseTestController extends TestCase
{
    /**
     * @var CallbackCatcher Callback
     */
    protected static $callbackCatcher;

    protected function newTestCase($result): CoreTestCase
    {
        return new CoreTestCase($this, self::$callbackCatcher, $result);
    }

    protected static function getClient(): ApimaticCalculatorClient
    {
        self::$callbackCatcher = new CallbackCatcher();
        return ClientFactory::create(self::$callbackCatcher);
    }
}
